/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGuideRouteImport } from './routes/api/public/guide'
import { Route as ApiPublicHandoffRouteImport } from './routes/api/public/handoff'
import { Route as ApiPublicInspectRouteImport } from './routes/api/public/inspect'
import { Route as ApiPublicResearchRouteImport } from './routes/api/public/research'
import { Route as ApiPublicSpeakRouteImport } from './routes/api/public/speak'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuideRoute = ApiPublicGuideRouteImport.update({
  id: '/api/public/guide',
  path: '/api/public/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHandoffRoute = ApiPublicHandoffRouteImport.update({
  id: '/api/public/handoff',
  path: '/api/public/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInspectRoute = ApiPublicInspectRouteImport.update({
  id: '/api/public/inspect',
  path: '/api/public/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResearchRoute = ApiPublicResearchRouteImport.update({
  id: '/api/public/research',
  path: '/api/public/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpeakRoute = ApiPublicSpeakRouteImport.update({
  id: '/api/public/speak',
  path: '/api/public/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/guide': typeof ApiPublicGuideRoute
  '/api/public/handoff': typeof ApiPublicHandoffRoute
  '/api/public/inspect': typeof ApiPublicInspectRoute
  '/api/public/research': typeof ApiPublicResearchRoute
  '/api/public/speak': typeof ApiPublicSpeakRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/guide': typeof ApiPublicGuideRoute
  '/api/public/handoff': typeof ApiPublicHandoffRoute
  '/api/public/inspect': typeof ApiPublicInspectRoute
  '/api/public/research': typeof ApiPublicResearchRoute
  '/api/public/speak': typeof ApiPublicSpeakRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/guide': typeof ApiPublicGuideRoute
  '/api/public/handoff': typeof ApiPublicHandoffRoute
  '/api/public/inspect': typeof ApiPublicInspectRoute
  '/api/public/research': typeof ApiPublicResearchRoute
  '/api/public/speak': typeof ApiPublicSpeakRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/guide'
    | '/api/public/handoff'
    | '/api/public/inspect'
    | '/api/public/research'
    | '/api/public/speak'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/guide'
    | '/api/public/handoff'
    | '/api/public/inspect'
    | '/api/public/research'
    | '/api/public/speak'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/api/public/guide'
    | '/api/public/handoff'
    | '/api/public/inspect'
    | '/api/public/research'
    | '/api/public/speak'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicGuideRoute: typeof ApiPublicGuideRoute
  ApiPublicHandoffRoute: typeof ApiPublicHandoffRoute
  ApiPublicInspectRoute: typeof ApiPublicInspectRoute
  ApiPublicResearchRoute: typeof ApiPublicResearchRoute
  ApiPublicSpeakRoute: typeof ApiPublicSpeakRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guide': {
      id: '/api/public/guide'
      path: '/api/public/guide'
      fullPath: '/api/public/guide'
      preLoaderRoute: typeof ApiPublicGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/handoff': {
      id: '/api/public/handoff'
      path: '/api/public/handoff'
      fullPath: '/api/public/handoff'
      preLoaderRoute: typeof ApiPublicHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inspect': {
      id: '/api/public/inspect'
      path: '/api/public/inspect'
      fullPath: '/api/public/inspect'
      preLoaderRoute: typeof ApiPublicInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/research': {
      id: '/api/public/research'
      path: '/api/public/research'
      fullPath: '/api/public/research'
      preLoaderRoute: typeof ApiPublicResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/speak': {
      id: '/api/public/speak'
      path: '/api/public/speak'
      fullPath: '/api/public/speak'
      preLoaderRoute: typeof ApiPublicSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicGuideRoute: ApiPublicGuideRoute,
  ApiPublicHandoffRoute: ApiPublicHandoffRoute,
  ApiPublicInspectRoute: ApiPublicInspectRoute,
  ApiPublicResearchRoute: ApiPublicResearchRoute,
  ApiPublicSpeakRoute: ApiPublicSpeakRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
